# SPDX-License-Identifier: GPL-2.0

dtb-$(CONFIG_ARCH_MXC) += \
			  imx8mm-icore-starterkit.dtb \
			  imx8mm-icore-ctouch2.dtb \
			  imx8mm-icore-ctouch2-amp10.dtb \
			  imx8mm-icore-ctouch2-rs232.dtb \
			  imx8mm-icore-ctouch2-rs232-amp10.dtb \
			  imx8mm-icore-ctouch2-rs232-yes7.dtb \
			  imx8mm-icore-ctouch2-yes7.dtb \
			  imx8mm-icore-ctouch2-yes10.dtb \
			  imx8mp-icore-2e-net-phy.dtb \
			  imx8mp-icore-2e-starterkit.dtb \
			  imx8mp-icore-ctouch2.dtb \
			  imx8mp-icore-ctouch2-amp10.dtb \
			  imx8mp-icore-starterkit.dtb \
			  imx8mp-icore-fasteth-ctouch2.dtb \
			  imx8mp-icore-fasteth-ctouch2-amp10.dtb \
			  imx8mp-icore-fasteth-starterkit.dtb \
			  imx8mp-smarcore-xtouch2.dtb \
			  imx8ulp-microgea-microdev-yes7.dtb \
			  imx93-icore-starterkit.dtb \
			  imx93-icore-ctouch2.dtb \
			  imx93-icore-ctouch2-amp10.dtb \
			  imx8qxp-icore-starterkit.dtb \
			  imx8qxp-icore-ctouch2.dtb \
			  imx8xq-smarcore-xtouch2.dtb

